name: requests_inspector
description: A Flutter package for logging REST-APIs and GraphQL requests and
  accessing it by Shaking your phone to get the RequestsInspector widget on your
  screen.
version: 4.0.4
homepage: https://github.com/Abdelazeem777/requests_inspector
# we can add screenshots here using screenshots key
# please check this link https://dart.dev/tools/pub/pubspec#screenshots

environment:
  sdk: ">=2.19.0 <3.0.0"
  flutter: ">=3.10.0"


dependencies:
  collection: ^1.18.0
  dio: ^5.7.0
  flutter:
    sdk: flutter
  gql: ^1.0.0+1
  graphql: ^5.1.3
  graphql_flutter: ^5.1.2
  provider: ^6.1.2
  shake:
    git:
      url: https://github.com/DatUET/sale_app_libraries
      ref: main
      path: shake
  share_plus: 7.2.2

dev_dependencies:
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter
